### ISSUE TITLE
Template parsing error: template: :1:2: executing "" at <index .RepoDigests 0>: error calling index: reflect: slice index out of range

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/publish-security-assessments#11]
Hi, I am trying to post the vulnerability scan results but I get the error:
`Template parsing error: template: :1:2: executing "" at <index .RepoDigests 0>: error calling index: reflect: slice index out of range`
![Screenshot 2021-06-01 at 19 28 00](https://user-images.githubusercontent.com/10193236/120366093-84827500-c30f-11eb-9975-a57b975c3a40.png)

My workflow looks like this:

    jobs:
      vulnerability_scan:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - run: docker build . -t bvdklinkenberg/webserver:${{ github.sha }}
            name: docker build
          - uses: Azure/container-scan@v0
            name: scan images for vulnerabilities
            id: container_scan
            continue-on-error: true
            with:
              image-name: bvdklinkenberg/webserver:${{ github.sha }}
          - uses: Azure/publish-security-assessments@v0
            name: post logs to app insights
            with:
              scan-results-path: ${{ steps.container_scan.outputs.scan-report-path }}
              connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
              subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}

What I am doing wrong here?

**Comment by bramvdklinkenberg** [comment]
Attached the full workflow logs
[logs_10.zip](https://github.com/Azure/publish-security-assessments/files/6579807/logs_10.zip)

**Comment by bramvandenklinkenberg** [comment]
@ajinkya599 @anraghun @sundargs2000 @Josh-01 do you guys have any idea maybe? :-)

**Comment by MoAhuja** [comment]
Ran into the same issue. You actually need to push the image before a digest is created (https://github.com/docker/cli/issues/728#issuecomment-434753398}

The code appears to be running docker inspect to retrieve manifest information about the image and then parsing out the digest from the JSON response. If you don't push your image and run 'docker inspect [image]' you end up with a RepoDigests that is empty. It results in the parser blowing up because it's missing critical info.
```
{
        "Id": "sha256:3e47a2f5243a4b5d34d138dfc4bb61b9e3df6d07a74e07ce598584e7ea7370fb",
        "RepoTags": [
            "***/contoso-website:latest"
        ],
        "RepoDigests": [],
...
}
```        

If you update your flow to actually push the image, you'll notice it actually gets populated

```
{
        "Id": "sha256:31663f400b88f6d9e5c1f47d0b01bb8935536745e21d52591f34e81512cbebc5",
        "RepoTags": [
            "***/contoso-website:latest"
        ],
        
        "RepoDigests": [
            "***/contoso-website@sha256:3277c6671b7585812a7abe41aa5f1f33f147a79cf915e561f68f6405a2322665"
        ],
...
}
```

All that said, it would be nice to be able to run a container scan + upload results without having to push the image to a registry.

**Comment by bramvdklinkenberg** [comment]
Hi @MoAhuja , thanks a lot for the info! Indeed with the docker push step before publish security assessments works!
Too bad you need to push the image to a registry first, hope they can/will adjust that.

**Comment by larryclaman** [comment]
@bramvandenklinkenberg, checking in on this ask from a few months back.  Could you review PR #18?
